CREATE TABLE user_verification
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at        TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at        TIMESTAMP WITHOUT TIME ZONE,
    verification_code VARCHAR(255)                            NOT NULL,
    expiry_date       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    user_id           BIGINT,
    CONSTRAINT pk_user_verification PRIMARY KEY (id)
);

CREATE TABLE users
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username       VARCHAR(50)                             NOT NULL,
    email          VARCHAR(100)                            NOT NULL,
    phone_number   VARCHAR(12)                             NOT NULL,
    firstname      VARCHAR(255)                            NOT NULL,
    lastname       VARCHAR(255)                            NOT NULL,
    birth_date     date,
    marital_status VARCHAR(255)                            NOT NULL,
    gender         VARCHAR(255)                            NOT NULL,
    weight         DOUBLE PRECISION                        NOT NULL,
    height         DOUBLE PRECISION                        NOT NULL,
    password       VARCHAR(100)                            NOT NULL,
    role           VARCHAR(255)                            NOT NULL,
    created_at     TIMESTAMP WITHOUT TIME ZONE,
    updated_at     TIMESTAMP WITHOUT TIME ZONE,
    is_enabled     BOOLEAN                                 NOT NULL,
    enabled_at     TIMESTAMP WITHOUT TIME ZONE,
    is_locked      BOOLEAN                                 NOT NULL,
    is_deleted     BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE user_verification
    ADD CONSTRAINT uc_user_verification_user UNIQUE (user_id);

ALTER TABLE user_verification
    ADD CONSTRAINT uc_user_verification_verification_code UNIQUE (verification_code);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_phone_number UNIQUE (phone_number);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

ALTER TABLE user_verification
    ADD CONSTRAINT FK_USER_VERIFICATION_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);